# Generated by Django 4.2.4 on 2023-09-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_to_do_data_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_data',
            old_name='dt',
            new_name='timestamp',
        ),
    ]
