# Generated by Django 4.2.4 on 2023-09-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_to_do_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
