# Generated by Django 4.2.4 on 2023-09-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_to_do_data_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_data',
            name='timestamp',
        ),
    ]
